In [1]:
from anova1_functions import *

In [2]:
df = pd.read_csv('crop_data.csv')

In [3]:
df

density  block  fertilizer       yield
0         1      1           1  177.228692
1         2      2           1  177.550041
2         1      3           1  176.408462
3         2      4           1  177.703625
4         1      1           1  177.125486
..      ...    ...         ...         ...
91        2      4           3  177.405292
92        1      1           3  178.141644
93        2      2           3  177.710613
94        1      3           3  177.687264
95        2      4           3  177.118176

[96 rows x 4 columns]

In [4]:
df = df[['fertilizer','yield']]

In [5]:
fert1 = df[df.fertilizer == 1]['yield'].values
fert2 = df[df.fertilizer == 2]['yield'].values
fert3 = df[df.fertilizer == 3]['yield'].values

In [6]:
data = pd.DataFrame({'first':fert1, 'second':fert2, 'third': fert3})
data

first      second       third
0   177.228692  176.479341  177.104186
1   177.550041  176.044342  178.079635
2   176.408462  177.412462  176.903422
3   177.703625  177.360818  177.540284
4   177.125486  177.385499  177.032710
5   176.778342  176.975808  178.286042
6   176.746302  177.379779  176.405410
7   177.061164  177.997995  176.430830
8   176.274949  176.434863  177.396331
9   177.967203  176.933265  176.925576
10  176.601300  175.983480  177.055046
11  177.030543  177.034093  177.344164
12  177.479507  176.436762  177.128368
13  176.874130  176.067745  177.168302
14  176.114388  177.121049  176.353941
15  176.008395  177.197721  179.060899
16  176.108313  176.603724  176.300517
17  178.357441  177.208171  177.593352
18  177.262445  177.148829  177.115245
19  176.918845  176.819077  177.794457
20  176.239016  176.999067  177.004038
21  176.573070  178.134605  178.036858
22  176.039298  176.429156  177.701366
23  176.817922  176.668323  177.632808
24  176.160587  176.895867  177.652275
25  177.226424  177.779493  177.100418
26  175.938533  176.414495  177.187967
27  177.164937  176.878898  177.405292
28  175.360840  177.580683  178.141644
29  177.276996  176.957269  177.710613
30  175.945444  175.747546  177.687264
31  175.882780  177.352595  177.118176

In [7]:
f_stat, f_score, f_table = ANOVA1_test_equality(data,0.1)

In [8]:
f_table

df         SS        MS        F     p-value
BetweenGroups   2   6.068047   3.03402  7.86275  0.00657371
WithinGroups   93  35.886186  0.385873        -           -
Total          95  41.954233         -        -           -

In [9]:
#checking whether result is correct or not with a library

import pingouin as pg
aov = pg.anova(dv='yield', between='fertilizer', data=df,
               detailed=True)
aov.round(3)

Source      SS  DF     MS      F  p-unc    np2
0  fertilizer   6.068   2  3.034  7.863  0.001  0.145
1      Within  35.886  93  0.386    NaN    NaN    NaN

/opt/anaconda3/lib/python3.7/site-packages/outdated/utils.py:18: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.3.11, the latest is 0.3.12.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  **kwargs


In [10]:
#Correct !

# now checking if functions regarding to contrasts work

In [17]:
#returns True 
contrast = np.array([0,-1,1])
ANOVA1_is_contrast(contrast)

True

In [18]:
not_contrast = np.array([0,-1,1,0,1,1]).reshape(2,3)
ANOVA1_all_contrast(not_contrast)


False

In [19]:
contrast_and_orthogonal = np.array([0.5,0.5,-1,1,-1,0]).reshape(2,3)
contrast_and_orthogonal

array([[ 0.5,  0.5, -1. ],
       [ 1. , -1. ,  0. ]])

In [20]:
ANOVA1_all_contrast(contrast_and_orthogonal)

True

In [21]:
n_list = []
for col in data.columns:
    
    n_list.append(len(data[col]))
    
n_list
    

[32, 32, 32]

In [23]:
#orthogonality function check
ANOVA1_all_orthogonal(contrast_and_orthogonal,n_list)

True

Let's look at the mean differences

In [24]:
#starting with contrast and ortogonal C Matrix

contrast_and_orthogonal

array([[ 0.5,  0.5, -1. ],
       [ 1. , -1. ,  0. ]])

In [25]:
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = contrast_and_orthogonal, method = 'best')

C is all contrasts and also orthogonal, Comparing between Scheffe(Th-2.8)  and Sidak.. 
Intervals of Scheffe is  narrower:
Scheffe interval length for the first difference:  0.6748597925268087
Sidak interval length for the first difference:  0.8671928980310426


Difference in mean        lb        ub
0           -0.511041 -0.848471 -0.173611
1           -0.176169 -0.625316  0.272978

In [26]:
ANOVA1_test_linear_combs(data, alpha = 0.1, C = contrast_and_orthogonal, method = 'best')

C is all contrasts and also orthogonal, Comparing between Scheffe(Th-2.8)  and Sidak.. 
Intervals of Scheffe is  narrower:
Scheffe interval length for the first difference:  0.6748597925268087
Sidak interval length for the first difference:  0.8671928980310426


Difference in mean        lb        ub     p-val decision
0   -0.5110412133897455 -0.848471 -0.173611  0.220563   accept
1  -0.17616872530919636 -0.625316  0.272978  0.201080   accept

In [33]:
#trying without best
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = contrast_and_orthogonal, method = 'Scheffe')

C is all contrasts and also orthogonal, Comparing between Scheffe(Th-2.8)  and Sidak.. 
Returning Scheffe Test Result


Difference in mean        lb        ub
0           -0.511041 -0.848471 -0.173611
1           -0.176169 -0.625316  0.272978

In [34]:
#testing the result with an inapropraite method
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = contrast_and_orthogonal, method = 'Bonferonni')

C is all contrasts and also orthogonal, method should be Scheffe and Sidak. Please select appropriate method.


p-val > alpha, thus we accept the both null hypothesis

In [29]:
#Lets Look at the pairwise differneces

pairwise_contrast = np.array([0,-1,1,1,-1,0,-1,0,1]).reshape(3,3)
pairwise_contrast

array([[ 0, -1,  1],
       [ 1, -1,  0],
       [-1,  0,  1]])

In [31]:
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = pairwise_contrast , method = 'best')

C is pairwise differences but not orthogonal, Comparing between Tukey and Bonferonni.. 
Intervals of Tukey is  narrower:
Tukey interval length for the first difference:  0.6455000000000001
Bonferonni interval length for the first difference:  1.1708929574837543


Difference in mean      lb      ub
0              0.4230  0.1002  0.7457
1              0.1762 -0.1466  0.4989
2              0.5991  0.2764  0.9218

In [10]:
ANOVA1_test_linear_combs(data, alpha = 0.1, C = pairwise_contrast , method = 'best')

C is pairwise differences but not orthogonal, Comparing between Tukey and Bonferonni.. 
Intervals of Tukey is  narrower:
Tukey interval length for the first difference:  0.6455000000000001
Bonferonni interval length for the first difference:  1.1708929574837543


Difference in mean      lb      ub   p-val decision
0              0.4230  0.1002  0.7457  0.0209   accept
1              0.1762 -0.1466  0.4989  0.4968   reject
2              0.5991  0.2764  0.9218  0.0010   accept

Reject only 2nd hypothesis resulted from 2nd. contrast [1,-1,0]

In [36]:
#let's look at linear combinations

linear_comb = np.array([0,-1,2,1,1,-1]).reshape(2,3)
linear_comb

array([[ 0, -1,  2],
       [ 1,  1, -1]])

In [38]:
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = linear_comb , method = 'best')

All linear combinations are not contrasts, Comparing between Scheffe(Th2.7) and Bonferonni.. 
Intervals of Scheffe is  narrower:
Scheffe interval length for the first difference:  1.2475740844813572
Bonferonni interval length for the first difference:  1.6130605688235278


Difference in mean          lb          ub
0          177.779127  177.155340  178.402914
1          176.334087  175.851758  176.816417

In [39]:
ANOVA1_test_linear_combs(data, alpha = 0.1, C = linear_comb , method = 'best')

All linear combinations are not contrasts, Comparing between Scheffe(Th2.7) and Bonferonni.. 
Intervals of Scheffe is  narrower:
Scheffe interval length for the first difference:  1.2475740844813572
Bonferonni interval length for the first difference:  1.6130605688235562


Difference in mean          lb          ub     p-val decision
0  177.77912676034646  177.155340  178.402914  0.221191   accept
1  176.33408748283182  175.851758  176.816417  0.229430   accept

In [50]:
#finally, check with a all contrasts but not orthogonal C

conrasts_notOrthogonal = np.array([-1,1/2,1/2,1,1,-2]).reshape(2,3)
conrasts_notOrthogonal

array([[-1. ,  0.5,  0.5],
       [ 1. ,  1. , -2. ]])

In [51]:
ANOVA1_C1_linear_combs(data, alpha = 0.1, C = conrasts_notOrthogonal , method = 'best')

C is all contrast but not orthogonal, Comparing between Scheffe(Th-2.8) and Bonferonni.. 
Intervals of Scheffe is  narrower:
Scheffe interval length for the first difference:  0.6748597925268087
Bonferonni interval length for the first difference:  0.8722542290520421


Difference in mean        lb        ub
0            0.387647  0.050217  0.725077
1           -1.022082 -1.696942 -0.347223